/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cadastrar-usuario` | `/cadastrar-usuario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-data` | `/create-data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/view-data` | `/view-data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar-dados` | `/editar-dados`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cadastrar-usuario` | `/cadastrar-usuario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create-data` | `/create-data`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/view-data` | `/view-data`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/editar-dados` | `/editar-dados`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cadastrar-usuario${`?${string}` | `#${string}` | ''}` | `/cadastrar-usuario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create-data${`?${string}` | `#${string}` | ''}` | `/create-data${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/view-data${`?${string}` | `#${string}` | ''}` | `/view-data${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/editar-dados${`?${string}` | `#${string}` | ''}` | `/editar-dados${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cadastrar-usuario` | `/cadastrar-usuario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-data` | `/create-data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/view-data` | `/view-data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar-dados` | `/editar-dados`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
